### ISSUE TITLE
Requires Python, Visual C and Admin permission to run

### ISSUE THREAD

**Issue by digitalspider** [brandiqa/mobx-crud-example#1]
Hi,

I went through the source code on this project and it looks awesome. 

However after downloading it and trying to compile this project, I hit a lot of issues. Firstly it requires Python 2.7. Why an NPM project needs this is beyond me. Second I found that "windows-build-tools" had to be installed, and this required administrative permissions on windows. Even after doing that, and then running "yarn install", I'm still getting the below error.

Not being an expert in the Node.js world, I'm going to give up on this for now and try find a different sample code base.

> ode-sass\\build\\binding.sln\" on node 1 (default targets).
> ValidateSolutionConfiguration:
>   Building solution configuration \"Release|x64\".
> MSBUILD : error MSB3428: Could not load the Visual C++ component \"VCBuild.exe\". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\\code\\mobx-crud-example\
> ode_modules\
> ode-sass\\build\\binding.sln]
> Done Building Project \"C:\\code\\mobx-crud-example\
> ode_modules\
> ode-sass\\build\\binding.sln\" (default targets) -- FAILED.
> 
> Build FAILED.
> 
> \"C:\\code\\mobx-crud-example\
> ode_modules\
> ode-sass\\build\\binding.sln\" (default target) (1) ->
> (_src_\\libsass target) ->
>   MSBUILD : error MSB3428: Could not load the Visual C++ component \"VCBuild.exe\". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\\code\\mobx-crud-example\
> ode_modules\
> ode-sass\\build\\binding.sln
>     0 Warning(s)
>     1 Error(s)
> Time Elapsed 00:00:01.26
> gyp ERR! build error
> gyp ERR! stack Error: `C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\\code\\mobx-crud-example\
> ode_modules\
> ode-gyp\\lib\\build.js:285:23)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Windows_NT 10.0.14393
> gyp ERR! command \"C:\\\\apps\\\
> odejs\\\
> ode.exe\" \"C:\\\\code\\\\mobx-crud-example\\\
> ode_modules\\\
> ode-gyp\\\\bin\\\
> ode-gyp.js\" \"rebuild\" \"--verbose\" \"--libsass_ext=\" \"--libsass_cflags=\" \"--libsass_ldflags=\" \"--libsass_library=\"
> gyp ERR! cwd C:\\code\\mobx-crud-example\
> ode_modules\
> ode-sass
> gyp ERR! node -v v8.9.4
> gyp ERR! node-gyp -v v3.6.0
> gyp ERR! not ok

Really hope that maybe this could be looked at and the setup/prerequisites documentation updated.

**Comment by brandiqa** [comment]
I believe its a problem that happens in Windows caused by the dependency Node Sass. Here is the explanation: https://github.com/sass/node-sass/issues/2117. The problem seems to be specific to Node 8.

Try using NodeJS 6 to install the dependencies. Use nvm for windows to switch between Node versions.

**Comment by brandiqa** [comment]
The problem is caused by missing dependencies required for node-gyph to compile in Windows. You need follow these instructions to properly install it: https://github.com/nodejs/node-gyp#on-windows. If you want a simple solution, just  setup the project in Linux or Mac. They already have the necessary dependencies. A lot of web-based NodeJS frameworks are dependent on node-gyph.
